### PR TITLE
Alter S3 uploader config for large uploads to Scaleway

### PR DESCRIPTION
**Pull request by anacrolix**
Implements https://github.com/benbjohnson/litestream/issues/276#issuecomment-1020785492.

### CODE REVIEW

**Comment by benbjohnson** [comment]
@anacrolix I think this needs to be configurable as I'm not sure the performance effects of adjusting the part size and count.

**Review by benbjohnson — CHANGES_REQUESTED** [review]
@anacrolix I think this needs to be configurable as I'm not sure the performance effects of adjusting the part size and count.

**Comment by benbjohnson** [comment]
@anacrolix I'm going to close this PR out for now. Let me know if you want it reopened. 👍

**Comment by anacrolix** [comment]
Perhaps it's worth trying with this as it has broader compatibility, and working back the other way if issues are found? For example a configuration option could instead increase the allowed part count and decrease the size.

**Comment by benbjohnson** [comment]
Yeah, I'm not opposed to changing the defaults but I think it'll need testing to understand the implications. Also, the new settings in this PR put the part size at 100MB and IIRC the uploader defaults to a concurrency of 8. I'm not sure what the heap requirements are per part but I'm a little concerned about making it OOM on small VM instances.

**Pull request closed without merging**
